name: Necesito ayuda de programación en C
description: Usá este template si necesitás ayuda con las commons, gcc, sockets, threads o C en general.
labels: ['programacion-c', 'api-linux-threads-semaforos-etc']
projects: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 🖋️ Descripción
      description: |
        Contanos cuál es el contexto de tu duda o problema, cuál es el comportamiento que esperabas y el que obtuviste.
        No olvides buscar primero en el buscador de issues por si la duda ya fue resuelta antes.
        Si no se resuelve pero creés que el issue está relacionado, podés citarlo con un #.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: docs
    attributes:
      label: 📚 Búsqueda en documentación/foros
      description: |
        Contanos si investigaste sobre el tema en Google o foros, y si encontraste algún post que sea de utilidad para darnos más contexto sobre el problema.
        En caso de tener una duda con alguna función de Linux, recomendamos consultar primero las [manpages](https://man7.org/linux/man-pages/index.html).
        Si es una función de las commons, la [documentación](https://faq.utnso.com.ar/commons-docs) también puede resultar muy útil.
    validations:
      required: false
  - type: textarea
    id: code
    attributes:
      label: 📄 Código relevante
      description: |
        No subas capturas de pantalla, copiá el código relevante a tu problema y pegalo acá.
        Podés darle formato código seleccionando todas las líneas a la vez y pulsando Ctrl + 'e'.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: 🐛 Cómo reproducir el error
      description: |
        Contanos qué pasos seguiste para llegar hasta la duda o problema.
        Si se trata de comandos por consola, no subas capturas de pantalla, copiá el texto y pegalo acá.
        Podés darle formato código seleccionando todas las líneas a la vez y pulsando Ctrl + 'e'.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 💻 Logs
      description: |
        ¿Lo corriste por consola, usando el [debugger](https://faq.utnso.com.ar/debugger) o con [Valgrind](https://faq.utnso.com.ar/valgrind)? Copiá el texto y pegalo acá.
        Podés darle formato código seleccionando todas las líneas a la vez y pulsando Ctrl + 'e'.
        Si el output es muy extenso, sentite libre de adjuntar un archivo de texto en su lugar.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: 📝 Normas del foro
      description: Al subir el issue, asumimos que leíste los [lineamientos del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md)
      options:
        - label: Leí los lineamientos del foro
          required: true
