name: Necesito ayuda con otra herramienta
description: Usá este template si necesitás ayuda con el IDE, Git u otra herramienta.
labels: ['herramientas-ide-git-vms-etc :wrench:']
projects: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 🖋️ Descripción
      description: |
        Contanos cuál es el contexto de tu duda o problema.
        No olvides buscar primero en el buscador de issues por si la duda ya fue resuelta antes.
        Si no se resuelve tu duda pero creés que el issue está relacionado, podés citarlo con un #.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: docs
    attributes:
      label: 🔎 Búsqueda en foros
      description: |
        Contanos si investigaste sobre el tema en Google o en foros, y si encontraste algún post que sea de utilidad para darnos más contexto sobre el problema.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: 🐛 Cómo reproducir el error
      description: |
        Contanos qué pasos seguiste en la interfaz de usuario para llegar hasta la duda o problema.
        Si se trata de comandos por consola, no subas capturas de pantalla, copiá el texto y pegalo acá.
        Podés darle formato código seleccionando todas las líneas a la vez y pulsando Ctrl + 'e'.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 💻 Logs
      description: |
        Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos más contexto, no subas capturas de pantalla, copiá el texto y pegalo acá.
        Podés darle formato código seleccionando todas las líneas a la vez y pulsando Ctrl + 'e'.
        Si el output es muy extenso, sentite libre de adjuntar un archivo de texto en su lugar.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: 📝 Normas del foro
      description: Al subir el issue, asumimos que leíste los [lineamientos del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md)
      options:
        - label: Leí los lineamientos del foro
          required: true

